/**
 * AccountingEntriesTab Component
 *
 * Displays accounting entries generated by GL rules evaluation.
 * This is a read-only view - recognition is handled automatically by batch processing.
 *
 * Features:
 * - Summary cards showing totals and status counts
 * - Filter row with date range, status dropdown
 * - Data table with expandable rows showing entry details
 * - Pagination controls
 */

import { useState, useEffect, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FileText,
  Clock,
  CheckCircle,
  RotateCcw,
  ChevronDown,
  ChevronRight,
  AlertCircle,
  Calendar,
  Filter,
  RefreshCw,
  Download,
  Hash,
  ExternalLink,
} from 'lucide-react';
import { DatePicker } from '@jetsetgo/shared-components';
import {
  useAccountingEntries,
  AccountingEntriesFilters,
} from '../../hooks/useAccountingEntries';
import {
  AccountingEntry,
  AccountingEntryStatus,
  ACCOUNTING_ENTRY_STATUSES,
  Account,
} from '../../types/gl-rules';

interface AccountingEntriesTabProps {
  /** Available GL accounts for filtering */
  accounts: Account[];
  /** Callback to navigate to the GL Batch Runs tab with a specific batch highlighted */
  onNavigateToBatch?: (batchId: number) => void;
}

/**
 * Format currency amount
 */
function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

/**
 * Format date for display
 */
function formatDate(dateString: string | null): string {
  if (!dateString) return '-';
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

/**
 * Format date for input field
 */
function formatDateForInput(dateString: string | null): string {
  if (!dateString) return '';
  return dateString.split('T')[0];
}

/**
 * Status badge component
 */
function StatusBadge({ status }: { status: AccountingEntryStatus }) {
  const config = {
    pending: {
      label: 'Pending',
      icon: Clock,
      bgColor: 'var(--color-neutral-100)',
      textColor: 'var(--color-neutral-700)',
      iconColor: 'var(--color-neutral-500)',
    },
    recognized: {
      label: 'Recognized',
      icon: CheckCircle,
      bgColor: 'var(--color-success-50)',
      textColor: 'var(--color-success-700)',
      iconColor: 'var(--color-success-500)',
    },
    reversal: {
      label: 'Reversal',
      icon: RotateCcw,
      bgColor: 'var(--color-warning-50)',
      textColor: 'var(--color-warning-700)',
      iconColor: 'var(--color-warning-500)',
    },
  };

  const { label, icon: Icon, bgColor, textColor, iconColor } = config[status];

  return (
    <span
      className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium"
      style={{ backgroundColor: bgColor, color: textColor }}
    >
      <Icon size={12} style={{ color: iconColor }} />
      {label}
    </span>
  );
}

/**
 * Summary card component
 */
function SummaryCard({
  title,
  value,
  subtitle,
  icon: Icon,
  color,
}: {
  title: string;
  value: string | number;
  subtitle?: string;
  icon: React.ElementType;
  color: string;
}) {
  return (
    <div
      className="card p-4"
      style={{ borderLeft: `4px solid ${color}` }}
    >
      <div className="flex items-start justify-between">
        <div>
          <p
            className="text-sm font-medium"
            style={{ color: 'var(--color-text-secondary)' }}
          >
            {title}
          </p>
          <p
            className="text-2xl font-bold mt-1"
            style={{ color: 'var(--color-text)' }}
          >
            {value}
          </p>
          {subtitle && (
            <p
              className="text-xs mt-1"
              style={{ color: 'var(--color-text-muted)' }}
            >
              {subtitle}
            </p>
          )}
        </div>
        <div
          className="p-2 rounded-lg"
          style={{ backgroundColor: `${color}15` }}
        >
          <Icon size={20} style={{ color }} />
        </div>
      </div>
    </div>
  );
}

/**
 * Loading skeleton for the table
 */
function TableSkeleton() {
  return (
    <div className="card overflow-hidden">
      <div className="animate-pulse">
        {/* Header */}
        <div
          className="px-6 py-4"
          style={{
            backgroundColor: 'var(--color-neutral-50)',
            borderBottom: '1px solid var(--color-border)',
          }}
        >
          <div className="flex gap-4">
            {[1, 2, 3, 4, 5, 6].map((i) => (
              <div
                key={i}
                className="h-4 rounded"
                style={{
                  backgroundColor: 'var(--color-neutral-200)',
                  width: `${60 + i * 20}px`,
                }}
              />
            ))}
          </div>
        </div>
        {/* Rows */}
        {[1, 2, 3, 4, 5].map((row) => (
          <div
            key={row}
            className="px-6 py-4 flex gap-4"
            style={{ borderBottom: '1px solid var(--color-border)' }}
          >
            {[1, 2, 3, 4, 5, 6].map((col) => (
              <div
                key={col}
                className="h-4 rounded"
                style={{
                  backgroundColor: 'var(--color-neutral-100)',
                  width: `${80 + col * 15}px`,
                }}
              />
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}

/**
 * Empty state component
 */
function EmptyState({ hasFilters }: { hasFilters: boolean }) {
  return (
    <div className="card">
      <div className="p-12 text-center">
        <FileText
          size={48}
          style={{ color: 'var(--color-neutral-400)', margin: '0 auto' }}
        />
        <h3
          className="mt-4"
          style={{
            fontSize: 'var(--text-lg)',
            fontWeight: 'var(--font-weight-semibold)',
            color: 'var(--color-text)',
          }}
        >
          {hasFilters ? 'No entries found' : 'No accounting entries yet'}
        </h3>
        <p
          className="mt-2 max-w-md mx-auto"
          style={{
            fontSize: 'var(--text-sm)',
            color: 'var(--color-text-secondary)',
          }}
        >
          {hasFilters
            ? 'Try adjusting your filters to see more results'
            : 'Accounting entries will appear here after GL batch processing runs'}
        </p>
      </div>
    </div>
  );
}

/**
 * Expandable row component for entry details
 */
function EntryRow({
  entry,
  index,
  onNavigateToBatch,
}: {
  entry: AccountingEntry;
  index: number;
  onNavigateToBatch?: (batchId: number) => void;
}) {
  const [isExpanded, setIsExpanded] = useState(false);

  // Calculate debit/credit from amount
  const isDebit = entry.amount < 0;
  const debitAmount = isDebit ? Math.abs(entry.amount) : 0;
  const creditAmount = !isDebit ? entry.amount : 0;

  return (
    <>
      <motion.tr
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.2, delay: index * 0.02 }}
        onClick={() => setIsExpanded(!isExpanded)}
        className="cursor-pointer hover:bg-neutral-50 transition-colors"
        style={{ borderBottom: '1px solid var(--color-border)' }}
      >
        <td className="px-4 py-3">
          <button
            className="p-1 rounded hover:bg-neutral-100 transition-colors"
            style={{ color: 'var(--color-text-secondary)' }}
          >
            {isExpanded ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
          </button>
        </td>
        <td
          className="px-4 py-3"
          style={{
            fontSize: 'var(--text-sm)',
            color: 'var(--color-text-secondary)',
          }}
        >
          {formatDate(entry.created_at)}
        </td>
        <td
          className="px-4 py-3"
          style={{
            fontSize: 'var(--text-sm)',
            fontWeight: 'var(--font-weight-medium)',
            color: 'var(--color-text)',
          }}
        >
          {entry.account_name || 'Unknown Account'}
          {entry.account_external_id && (
            <span
              className="ml-2 text-xs"
              style={{ color: 'var(--color-text-muted)' }}
            >
              ({entry.account_external_id})
            </span>
          )}
        </td>
        <td className="px-4 py-3">
          <StatusBadge status={entry.status} />
        </td>
        <td
          className="px-4 py-3 text-right font-mono"
          style={{
            fontSize: 'var(--text-sm)',
            color: debitAmount > 0 ? 'var(--color-error-600)' : 'var(--color-text-muted)',
          }}
        >
          {debitAmount > 0 ? formatCurrency(debitAmount) : '-'}
        </td>
        <td
          className="px-4 py-3 text-right font-mono"
          style={{
            fontSize: 'var(--text-sm)',
            color: creditAmount > 0 ? 'var(--color-success-600)' : 'var(--color-text-muted)',
          }}
        >
          {creditAmount > 0 ? formatCurrency(creditAmount) : '-'}
        </td>
      </motion.tr>

      {/* Expanded details row */}
      <AnimatePresence>
        {isExpanded && (
          <motion.tr
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.2 }}
          >
            <td
              colSpan={6}
              style={{
                backgroundColor: 'var(--color-neutral-50)',
                borderBottom: '1px solid var(--color-border)',
              }}
            >
              <div className="px-8 py-4">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div>
                    <p
                      className="text-xs font-medium mb-1"
                      style={{ color: 'var(--color-text-muted)' }}
                    >
                      Batch Run #
                    </p>
                    {entry.batch_run_id ? (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          onNavigateToBatch?.(entry.batch_run_id!);
                        }}
                        className="text-sm font-mono inline-flex items-center gap-1 hover:underline"
                        style={{ color: 'var(--color-primary-600)' }}
                      >
                        <Hash size={12} />
                        {entry.batch_run_id}
                        <ExternalLink size={10} />
                      </button>
                    ) : (
                      <p
                        className="text-sm"
                        style={{ color: 'var(--color-text-muted)' }}
                      >
                        —
                      </p>
                    )}
                  </div>
                  <div>
                    <p
                      className="text-xs font-medium mb-1"
                      style={{ color: 'var(--color-text-muted)' }}
                    >
                      Booking Reference
                    </p>
                    <p
                      className="text-sm"
                      style={{ color: entry.booking_ref ? 'var(--color-text)' : 'var(--color-text-muted)' }}
                    >
                      {entry.booking_ref || '—'}
                    </p>
                  </div>
                  <div>
                    <p
                      className="text-xs font-medium mb-1"
                      style={{ color: 'var(--color-text-muted)' }}
                    >
                      Recognized At
                    </p>
                    <p
                      className="text-sm"
                      style={{ color: 'var(--color-text)' }}
                    >
                      {entry.recognised_at
                        ? formatDate(entry.recognised_at_local || entry.recognised_at)
                        : 'Not yet recognized'}
                    </p>
                  </div>
                  <div>
                    <p
                      className="text-xs font-medium mb-1"
                      style={{ color: 'var(--color-text-muted)' }}
                    >
                      Net Amount
                    </p>
                    <p
                      className="text-sm font-mono font-medium"
                      style={{
                        color: entry.amount >= 0
                          ? 'var(--color-success-600)'
                          : 'var(--color-error-600)',
                      }}
                    >
                      {formatCurrency(entry.amount)}
                    </p>
                  </div>
                </div>
              </div>
            </td>
          </motion.tr>
        )}
      </AnimatePresence>
    </>
  );
}

/**
 * Pagination component
 */
function Pagination({
  pagination,
  onPageChange,
}: {
  pagination: { page: number; page_size: number; total_items: number; total_pages: number };
  onPageChange: (page: number) => void;
}) {
  const { page, page_size, total_items, total_pages } = pagination;
  const startItem = (page - 1) * page_size + 1;
  const endItem = Math.min(page * page_size, total_items);

  // Generate page numbers to show
  const getPageNumbers = () => {
    const pages: (number | 'ellipsis')[] = [];
    const showPages = 5;

    if (total_pages <= showPages) {
      for (let i = 1; i <= total_pages; i++) {
        pages.push(i);
      }
    } else {
      // Always show first page
      pages.push(1);

      if (page > 3) {
        pages.push('ellipsis');
      }

      // Show pages around current
      for (let i = Math.max(2, page - 1); i <= Math.min(total_pages - 1, page + 1); i++) {
        pages.push(i);
      }

      if (page < total_pages - 2) {
        pages.push('ellipsis');
      }

      // Always show last page
      if (total_pages > 1) {
        pages.push(total_pages);
      }
    }

    return pages;
  };

  if (total_items === 0) return null;

  return (
    <div className="flex items-center justify-between px-4 py-3">
      <p
        className="text-sm"
        style={{ color: 'var(--color-text-secondary)' }}
      >
        Showing {startItem} - {endItem} of {total_items} entries
      </p>
      <div className="flex items-center gap-1">
        <button
          onClick={() => onPageChange(page - 1)}
          disabled={page === 1}
          className="px-3 py-1.5 text-sm rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          style={{
            color: 'var(--color-text-secondary)',
            backgroundColor: 'var(--color-neutral-100)',
          }}
        >
          Prev
        </button>
        {getPageNumbers().map((p, i) =>
          p === 'ellipsis' ? (
            <span
              key={`ellipsis-${i}`}
              className="px-2"
              style={{ color: 'var(--color-text-muted)' }}
            >
              ...
            </span>
          ) : (
            <button
              key={p}
              onClick={() => onPageChange(p)}
              className="w-8 h-8 text-sm rounded-md transition-colors"
              style={{
                color: page === p ? 'white' : 'var(--color-text-secondary)',
                backgroundColor:
                  page === p ? 'var(--color-primary-600)' : 'var(--color-neutral-100)',
                fontWeight: page === p ? 'var(--font-weight-medium)' : 'normal',
              }}
            >
              {p}
            </button>
          )
        )}
        <button
          onClick={() => onPageChange(page + 1)}
          disabled={page === total_pages}
          className="px-3 py-1.5 text-sm rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          style={{
            color: 'var(--color-text-secondary)',
            backgroundColor: 'var(--color-neutral-100)',
          }}
        >
          Next
        </button>
      </div>
    </div>
  );
}

/**
 * Generate CSV content from accounting entries
 */
function generateEntriesCsv(entries: AccountingEntry[]): string {
  const headers = ['Date', 'GL Account', 'Account Code', 'Status', 'Debit', 'Credit', 'Booking Ref', 'Batch Run #'];
  const rows = entries.map((entry) => {
    const isDebit = entry.amount < 0;
    const debitAmount = isDebit ? Math.abs(entry.amount).toFixed(2) : '';
    const creditAmount = !isDebit && entry.amount > 0 ? entry.amount.toFixed(2) : '';
    return [
      entry.created_at ? new Date(entry.created_at).toLocaleDateString('en-US') : '',
      entry.account_name || '',
      entry.account_external_id || '',
      entry.status,
      debitAmount,
      creditAmount,
      entry.booking_ref || '',
      entry.batch_run_id ? entry.batch_run_id.toString() : '',
    ].map((v) => `"${v}"`).join(',');
  });
  return [headers.join(','), ...rows].join('\n');
}

export function AccountingEntriesTab({ accounts, onNavigateToBatch }: AccountingEntriesTabProps) {
  const {
    entries,
    summary,
    loading,
    error,
    pagination,
    filters,
    setFilters,
    resetFilters,
    fetchEntries,
    fetchSummary,
    goToPage,
  } = useAccountingEntries();

  const [isInitialized, setIsInitialized] = useState(false);

  // Date picker state
  const [showStartPicker, setShowStartPicker] = useState(false);
  const [showEndPicker, setShowEndPicker] = useState(false);
  const startDateButtonRef = useRef<HTMLButtonElement>(null);
  const endDateButtonRef = useRef<HTMLButtonElement>(null);

  // Initial data load - only run once on mount
  useEffect(() => {
    if (!isInitialized) {
      Promise.all([
        fetchEntries(filters, 1, 20),
        fetchSummary(filters),
      ]).then(() => {
        setIsInitialized(true);
      });
    }
  }, [isInitialized]); // eslint-disable-line react-hooks/exhaustive-deps

  // Handle filter changes
  const handleFilterChange = useCallback(
    (key: keyof AccountingEntriesFilters, value: string | number | null) => {
      const newFilters = { ...filters, [key]: value };
      setFilters(newFilters);
      // Fetch with new filters
      Promise.all([
        fetchEntries(newFilters, 1, pagination.page_size),
        fetchSummary(newFilters),
      ]);
    },
    [filters, setFilters, fetchEntries, fetchSummary, pagination.page_size]
  );

  // Handle refresh
  const handleRefresh = useCallback(() => {
    Promise.all([
      fetchEntries(filters, pagination.page, pagination.page_size),
      fetchSummary(filters),
    ]);
  }, [fetchEntries, fetchSummary, filters, pagination.page, pagination.page_size]);

  // Handle CSV export
  const handleCsvExport = useCallback(() => {
    if (entries.length === 0) return;
    const csv = generateEntriesCsv(entries);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `accounting-entries-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  }, [entries]);

  // Check if filters are active
  const hasActiveFilters =
    filters.status !== null ||
    filters.accountId !== null ||
    filters.search !== '';

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <SummaryCard
          title="Total Entries"
          value={summary.totalCount}
          subtitle={`${formatCurrency(summary.totalAmount)} net`}
          icon={FileText}
          color="var(--color-primary-500)"
        />
        <SummaryCard
          title="Pending"
          value={summary.pendingCount}
          subtitle="Awaiting recognition"
          icon={Clock}
          color="var(--color-neutral-500)"
        />
        <SummaryCard
          title="Recognized"
          value={summary.recognizedCount}
          subtitle={formatCurrency(summary.totalCredit)}
          icon={CheckCircle}
          color="var(--color-success-500)"
        />
        <SummaryCard
          title="Reversals"
          value={summary.reversalCount}
          subtitle={formatCurrency(summary.totalDebit)}
          icon={RotateCcw}
          color="var(--color-warning-500)"
        />
      </div>

      {/* Filters Row */}
      <div className="card p-4">
        <div className="flex flex-wrap items-center gap-4">
          {/* Date Range */}
          <div className="flex items-center gap-2">
            <Calendar size={16} style={{ color: 'var(--color-text-muted)' }} />
            <button
              ref={startDateButtonRef}
              onClick={() => setShowStartPicker(true)}
              className="input py-1.5 px-3 text-sm flex items-center gap-2"
              style={{ width: '150px' }}
            >
              <span style={{ color: filters.startDate ? 'var(--color-text-primary)' : 'var(--color-text-muted)' }}>
                {filters.startDate ? new Date(filters.startDate).toLocaleDateString('en-AU', { day: 'numeric', month: 'short' }) : 'Start'}
              </span>
            </button>
            <AnimatePresence>
              {showStartPicker && (
                <DatePicker
                  selectedDate={filters.startDate ? new Date(filters.startDate) : new Date()}
                  maxDate={filters.endDate ? new Date(filters.endDate) : undefined}
                  onSelect={(date) => {
                    handleFilterChange('startDate', date.toISOString().split('T')[0]);
                    setShowStartPicker(false);
                  }}
                  onClose={() => setShowStartPicker(false)}
                  anchorEl={startDateButtonRef.current}
                />
              )}
            </AnimatePresence>
            <span style={{ color: 'var(--color-text-muted)' }}>to</span>
            <button
              ref={endDateButtonRef}
              onClick={() => setShowEndPicker(true)}
              className="input py-1.5 px-3 text-sm flex items-center gap-2"
              style={{ width: '150px' }}
            >
              <span style={{ color: filters.endDate ? 'var(--color-text-primary)' : 'var(--color-text-muted)' }}>
                {filters.endDate ? new Date(filters.endDate).toLocaleDateString('en-AU', { day: 'numeric', month: 'short' }) : 'End'}
              </span>
            </button>
            <AnimatePresence>
              {showEndPicker && (
                <DatePicker
                  selectedDate={filters.endDate ? new Date(filters.endDate) : new Date()}
                  minDate={filters.startDate ? new Date(filters.startDate) : undefined}
                  onSelect={(date) => {
                    handleFilterChange('endDate', date.toISOString().split('T')[0]);
                    setShowEndPicker(false);
                  }}
                  onClose={() => setShowEndPicker(false)}
                  anchorEl={endDateButtonRef.current}
                />
              )}
            </AnimatePresence>
          </div>

          {/* Status Filter */}
          <div className="flex items-center gap-2">
            <Filter size={16} style={{ color: 'var(--color-text-muted)' }} />
            <select
              value={filters.status || ''}
              onChange={(e) =>
                handleFilterChange(
                  'status',
                  e.target.value ? (e.target.value as AccountingEntryStatus) : null
                )
              }
              className="input py-1.5 px-3 text-sm"
              style={{ minWidth: '140px' }}
            >
              <option value="">All Status</option>
              {ACCOUNTING_ENTRY_STATUSES.map((status) => (
                <option key={status} value={status}>
                  {status.charAt(0).toUpperCase() + status.slice(1)}
                </option>
              ))}
            </select>
          </div>

          {/* Account Filter */}
          <select
            value={filters.accountId || ''}
            onChange={(e) =>
              handleFilterChange(
                'accountId',
                e.target.value ? parseInt(e.target.value, 10) : null
              )
            }
            className="input py-1.5 px-3 text-sm"
            style={{ minWidth: '180px' }}
          >
            <option value="">All Accounts</option>
            {accounts.map((account) => (
              <option key={account.id} value={account.id}>
                {account.name} ({account.external_id})
              </option>
            ))}
          </select>

          {/* Spacer */}
          <div className="flex-1" />

          {/* Reset Filters */}
          {hasActiveFilters && (
            <button
              onClick={() => {
                resetFilters();
                const defaultFilters = {
                  startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
                  endDate: new Date().toISOString().split('T')[0],
                  status: null,
                  accountId: null,
                  search: '',
                };
                Promise.all([
                  fetchEntries(defaultFilters, 1, pagination.page_size),
                  fetchSummary(defaultFilters),
                ]);
              }}
              className="text-sm px-3 py-1.5 rounded-md hover:bg-neutral-100 transition-colors"
              style={{ color: 'var(--color-text-secondary)' }}
            >
              Reset Filters
            </button>
          )}

          {/* CSV Export Button */}
          <button
            onClick={handleCsvExport}
            disabled={entries.length === 0}
            className="flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-md hover:bg-neutral-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ color: 'var(--color-text-secondary)' }}
            title="Export current entries to CSV"
          >
            <Download size={16} />
            CSV
          </button>

          {/* Refresh Button */}
          <button
            onClick={handleRefresh}
            disabled={loading}
            className="p-2 rounded-md hover:bg-neutral-100 transition-colors disabled:opacity-50"
            style={{ color: 'var(--color-text-secondary)' }}
            title="Refresh"
          >
            <RefreshCw size={18} className={loading ? 'animate-spin' : ''} />
          </button>
        </div>
      </div>

      {/* Error State */}
      {error && (
        <div
          className="card"
          style={{
            backgroundColor: 'var(--color-error-50)',
            borderColor: 'var(--color-error-200)',
          }}
        >
          <div className="p-4 flex items-center gap-3">
            <AlertCircle size={20} style={{ color: 'var(--color-error-500)' }} />
            <p style={{ color: 'var(--color-error-700)' }}>{error}</p>
          </div>
        </div>
      )}

      {/* Data Table */}
      {loading && !isInitialized ? (
        <TableSkeleton />
      ) : entries.length === 0 ? (
        <EmptyState hasFilters={hasActiveFilters} />
      ) : (
        <div className="card overflow-hidden">
          <table className="w-full">
            <thead>
              <tr
                style={{
                  backgroundColor: 'var(--color-neutral-50)',
                  borderBottom: '1px solid var(--color-border)',
                }}
              >
                <th className="w-10 px-4 py-3" />
                <th
                  className="text-left px-4 py-3"
                  style={{
                    fontSize: 'var(--text-sm)',
                    fontWeight: 'var(--font-weight-semibold)',
                    color: 'var(--color-text-secondary)',
                  }}
                >
                  Date
                </th>
                <th
                  className="text-left px-4 py-3"
                  style={{
                    fontSize: 'var(--text-sm)',
                    fontWeight: 'var(--font-weight-semibold)',
                    color: 'var(--color-text-secondary)',
                  }}
                >
                  GL Account
                </th>
                <th
                  className="text-left px-4 py-3"
                  style={{
                    fontSize: 'var(--text-sm)',
                    fontWeight: 'var(--font-weight-semibold)',
                    color: 'var(--color-text-secondary)',
                  }}
                >
                  Status
                </th>
                <th
                  className="text-right px-4 py-3"
                  style={{
                    fontSize: 'var(--text-sm)',
                    fontWeight: 'var(--font-weight-semibold)',
                    color: 'var(--color-text-secondary)',
                  }}
                >
                  Debit
                </th>
                <th
                  className="text-right px-4 py-3"
                  style={{
                    fontSize: 'var(--text-sm)',
                    fontWeight: 'var(--font-weight-semibold)',
                    color: 'var(--color-text-secondary)',
                  }}
                >
                  Credit
                </th>
              </tr>
            </thead>
            <tbody>
              {entries.map((entry, index) => (
                <EntryRow key={entry.id} entry={entry} index={index} onNavigateToBatch={onNavigateToBatch} />
              ))}
            </tbody>
          </table>

          {/* Pagination */}
          <div
            style={{
              borderTop: '1px solid var(--color-border)',
              backgroundColor: 'var(--color-neutral-50)',
            }}
          >
            <Pagination pagination={pagination} onPageChange={goToPage} />
          </div>
        </div>
      )}
    </div>
  );
}
